### ISSUE TITLE
Ask Juliana nicely for staging and production PG databases

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#108]
### Descriptive summary

We need to ask @jgorney for PostgreSQL databases for the (to be created) staging and production environments. The credentials should be stored in the encrypted credentials file for the application.

### Rationale

An in memory database would be, while hilarious, a terrible idea in staging/production.

**Comment by jgorney** [comment]
Trying to decipher why I need to be asked nicely. Because I'm grouchy?  Because you knew this would make me laugh (which it did)??  LOL.  

What are the databases for (so I can come up with relevant names).

**Comment by mcritchlow** [comment]
@jgorney - The databases are for this 'High Five' employee recognition application we're working on for internal communications. So I defer to your judgment on naming them :)

Glad I got a laugh out of that :innocent:

**Comment by jgorney** [comment]
Quick question:  The PostgreSQL databases that support our Atlassian products are version 9.6 - the highest supported platform for them (I check constantly, I'm itching to upgrade).  

All other PostgreSQL databases are version 10.5 - and I'd like to upgrade all of them to V11.1 (probably after the winter break).  

Is it OK to create this database in the V10.5 environment, given that this will interact with Confluence, I'm assuming?  In my opinion, I believe it will be OK to have this in the V10.5.

**Comment by mcritchlow** [comment]
@jgorney - definitely! our current docker development environment for this app is targeting 10.5 already https://github.com/ucsdlib/hifive/blob/master/docker-compose.yml#L20 so that sounds like a great plan.

**Comment by jhriv** [comment]
The latest and greatest DB should be good. this is Rails, not Java

**Comment by jgorney** [comment]
If available, can I get the IP addresses of the servers that will be connecting to these new databases, so I can grant access?
