### ISSUE TITLE
The Manager is not being sent emails

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#128]
### Descriptive summary

Perhaps related to #127 the manager is not being sent emails. We should probably look at what's the DB for the Users/Recognitions we have created so far.

### Related work
#127

**Comment by VivianChu** [comment]
@mcritchlow - I deleted the entire contents, recreated the schema and reloaded the employees data.  The email is being sent to the manager now. Jessica confirmed that she received the email.
