### ISSUE TITLE
Look into a caching strategy for LDAP employee query

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#15]
The reality is this doesn't change that often. Perhaps setup a local cached file, and then setup a cron job to periodically update the cache. This would significantly speed up rendering the form

**Comment by mcritchlow** [comment]
@VivianChu - Here's my thinking on this after going through it a bit more in my head. Curious what your thoughts are:

Generally, I think it would be good to move away from what the code is currently doing, which is a dynamic lookup for all library employees each time the form is loaded, and only the cname(uid) of the recognizee is stored in the Recogntion DB table. While this isn't terrible and worked out just fine for a demo, it causes one extra LDAP query (to get the Manager), and slows down the form load time. It also makes testing a bit harder for integration tests because I/we have the mock the LDAP query to get the form to load.

I'm thinking instead, perhaps we could:

1. Create an Employees table with the properties we get back from LDAP that are needed to send emails and generate the one other needed query (manager info). So those would be:
  -  `cn` or UID (e.g 'mcritchlow')
  - `name` (we'd combine last and first name i think here, used for the email)
  - `manager` (e.g 'jhilt')
  - `mail` (email address)
  - `displayName` (this is 'last, first' essentially, [good for the association select list](https://github.com/plataformatec/simple_form#associations))

2. Update the Recognition model to something like a `has_one` for Employee. Create migration(s) as needed here.

3. Update Recognition form to use an [association](https://github.com/plataformatec/simple_form#associations) instead of the current select/helper method that's using the LDAP query.

4. Update the `Ldap.employees` method to add additional needed columns and persist to the new DB table. Ideally, maybe there's a lastUpdated field to use as a filter to keep future queries short?

5. Add the employees population to the `db/seeds.rb` file. This would let a new dev or prod app get that dataset populated quickly

6. Add the [`whenever` gem](https://github.com/javan/whenever), or alternative if needed, to run the `Ldap.employees` query nightly to resolve any changes and update the DB.

7. Remove the `Ldap.manager` method as it's no longer needed (we'd have the manager already in the DB)

8. Update the 'Ldap.manager_info` method to not use the DN used via `Ldap.manager` and instead setup a filter on the `manager` field instead.

9. Update all the tests, write new tests, etc.

**Comment by mcritchlow** [comment]
@VivianChu - Ok great thanks, I'll start on that today. I'm not sure how long it will take.. Will keep you posted.

**Comment by mcritchlow** [comment]
@VivianChu - I've gotten 1, 2 and 3 done.

Unfortunately what I'm running into is records that don't have manager information available LDAP. Which is definitely going to be a problem if we always need to send an email to the manager of the supervisor. I'm not sure how else we're going to get it.

@dlasusa @tmarconi - I'm curious what your thoughts on this are. Is there anything we can do from a process standpoint so that this application can rely on the `manager` property always being set for employees in LDAP? If not, we're just going to need to rethink how we gather this info and the assumptions around it.

**Comment by dlasusa** [comment]
I can think of 2 issues with using the manager field in AD.  1) It could be absent (like you've encountered) 2)  It could be set and also be incorrect.  We can only update it if we get notified, and I'm not sure how often that happens.  Ideally, as with setting it in AD, we'd query an HR database directly.

**Comment by mcritchlow** [comment]
@dlasusa - hmm. ok. that's unfortunate then as it really doesn't give us much in the way of automated options for dealing with this. it sounds as though there potentially _is_ no reliable automated way of getting that information, which would suck..
