### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/hifive#192]
### Descriptive summary

- Hifive Version 1.1
- Release Manager: @mcritchlow @VivianChu
- Product Owner: Kacy
- Operations: @jhriv @rstanonik 

### To Verify

- [x] #189 
- [x] #190

**Comment by VivianChu** [comment]
@jhriv @rstanonik - Could you deploy new Hifive release to production at your earliest convenient?  Thanks

**Comment by rstanonik** [comment]
highfive was deployed to production this morning (6:00am)

**Comment by VivianChu** [comment]
Thanks Ron

**Comment by VivianChu** [comment]
@rstanonik - I just made a hotfix based on Kacy's request.  Could you deploy it to production at your earliest convenient again?  Thanks

**Comment by rstanonik** [comment]
I deployed it to production last night

**Comment by VivianChu** [comment]
Thanks so much Ron.
