### ISSUE TITLE
Update Ruby to 2.6.2

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#196]

**Comment by rstanonik** [comment]
After I update rbenv, I don't see 2.6.2.
Here are the most recent versions I see
rbenv install --list
  2.6.0-dev
  2.6.0-preview1
  2.6.0-preview2
  2.6.0-preview3
  2.6.0-rc1
  2.6.0-rc2
  2.6.0
  2.6.1
  2.7.0-dev

**Comment by mcritchlow** [comment]
@rstanonik - yeah, it literally just came out. I'm just dropping the ticket here as a reminder for me. This will take a few changes in the codebase/docker images. I'll keep you posted so we can coordinate on this when it's widely available. I'm guessing another day or two.

**Comment by rstanonik** [comment]
Let me clarify, I don't update rbenv, I do the following
cd ~/.rbenv
git pull
cd plugins/ruby-build
git pull

**Comment by mcritchlow** [comment]
Yep, that'll be handled by https://github.com/rbenv/ruby-build/pull/1288 but then i also need to wait until all the docker images are updated. Those usually take a bit longer in my experience.

**Comment by rstanonik** [comment]
When I do upgrade, then steps I normally do are
rbenv install 2.6.2
rbenv global 2.6.2
gem install bundler
gem install passenger
gem install execjs
gem install rails

Do you need all of these or just the bundler?

**Comment by mcritchlow** [comment]
yeah we don't need all of those. this should do the trick:

```
rbenv install 2.6.2
gem install bundler
```
When the app is deployed and it runs `bundle install` the rest of those gems will be installed.

In the future, you won't even have to install `bundler` as it comes with newer versions of Ruby built-in.
