### ISSUE TITLE
Finalize workflow expectations for v1

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#30]
### Descriptive summary

We need to finalize the sequence of approvals that are required for a submitted recognition.

Here are a list of questions:

1) Upon submission of a Recognition by Employee A, is there any approval required on behalf of the administration group? I'm _hoping_ the answer is no. Simply because it's additional overhead for the admin group, and the risk/liklihood of an employee at the library very _publicly_ saying something bad about another employee seems incredibly low. Even though the submission can be "anonymous" the Recognition is directly linked to the Employee creating it. Framed differently, is it worth making the application more complex to address what should never happen?

2) Upon submission of a Recognition by Employee A recognizing Employee B, my understanding is Employee B needs to be given the option of that Recognition being made public (via the RSS feed for LiSN or otherwise). What isn't clear to me is:
  - Does that approval need to happen prior to the email being sent to Employee B and their Manager?
  - Is this an opt-in or opt-out situation? Either way, how long do we give Employee B to respond?

### Rationale

We need answers to these fundamental workflow questions in order to be able to program the application to act correctly.

### Related work

#23 #5

**Comment by mcritchlow** [comment]
Per Jessica: We don't need to worry about (1) :raised_hands:

**Comment by mcritchlow** [comment]
@VivianChu - I know we still don't have feedback on the 2nd part, but i assume we'll need some kind of status. Maybe we can use [AR enums](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) for this? Seems like it might be a good fit?

**Comment by VivianChu** [comment]
@mcritchlow - AR enums seems like a good fit.  We can use one value for status like - enum status: [ :public]

**Comment by jessicahilt** [comment]
- Kacy approves pictures to be used in the recommendation. 
- Kacy approves opting out (rather than opting in). Kacy would like the option for someone to remove their name by clicking a link without a quick turnaround time (Matt discussed a long period, like a year). 
- Edit and delete from the admin "super group" side. 
- Perhaps edit and delete from the recommender only. 

Need from Kacy:
- text for emails. Employee and manager.

**Comment by jessicahilt** [comment]
Deadline: 20th of November. 

Let's bring in David to start branding now.

**Comment by jessicahilt** [comment]
Example email to employee: 
Dear Vinny,
 
You have been recognized for Service & Excellence  by Sue McGuiness. Please see the recognition below:
Please describe what the employee did and why it was important to the team/program/organization or how it contributed to the achievement of strategic objectives:Vinny possesses a special combination of knowledge, skill, communication, and sensitivity; the value of which cannot be overestimated or taken for granted in the HR work he does. I wish I could describe some detail of how he how he has worked with me in recent months, but that would be confidential :). Suffice it to say that Vinny knows how to translate HR policy into what I need to know, what I need to do, and when people need to know or do something. And he does it all with kindness, professionalism and a dash of well-timed humor.Namaste Vinny!
--
You can expect your recognition to appear in the Employee Appreciation & Recognition Program (EARP) blog within 2 business days.
 
If for some reason you do not want your submission to appear, or you would like it removed from the blog, please contact Colleen Garcia.
 
 
Kacy Vega
Internal Communications Director
UC San Diego Library | 858.534.7392 | kacyvega@ucsd.edu

![screen shot 2018-11-06 at 1 56 35 pm](https://user-images.githubusercontent.com/11340068/48096350-ce446680-e1cb-11e8-8b97-84b6d259cd7b.png)

**Comment by mcritchlow** [comment]
This is being addressed by more specific tickets/PRs, such as #78 #79 so closing this original abstract ticket
