### ISSUE TITLE
Try splitting out the postfix/email service into its own container

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#327]
### Descriptive summary
#320 added support for postfix by embedding it in the Dockerfile for the app. More ideally, we would have a separate container with the responsibility of sending email. Leaving the application container to run the app itself.

So, let's see if this is possible.

### Rationale

Separation of concerns, 1 service per container

**Comment by mcritchlow** [comment]
In addition to building our own solution, I've found a few dedicated projects for running postfix in an alpine container:
- https://github.com/smpio/postfix-docker (tested w/ our project and works)
- https://github.com/bokysan/docker-postfix (_testing in progress_, looks a bit more robust and uses environment variables, which would definitely be better)

**Comment by mcritchlow** [comment]
At the moment, after confirming that bokysan/docker-postfix works, I'm tempted to say we should use that as our solution. That said, I think we _might_ consider forking if we want to make some modification such as pinning the version of Alpine (which i think we'd want to).

**Comment by mcritchlow** [comment]
We should define a k8s networking policy for this container in the pod:

https://kubernetes.io/docs/concepts/services-networking/network-policies/

such that, only the application container is allowed to ingress to the postfix container

**Comment by VivianChu** [comment]
It looks like a good solution.

**Comment by mcritchlow** [comment]
Fixed in #318 , with the caveat that we're waiting on a merged PR upstream to fix the version of alpine.
