### ISSUE TITLE
Change Opt-Out Language on HighFive Email

### ISSUE THREAD

**Issue by jessicahilt** [ucsdlib/hifive#370]
From Kacy, through Zen Desk: 
We’ve received a request to make the opt-out language a bit clearer for the automated High Five email. See section highlighted in yellow for old language and new language we’re proposing below.
 
Proposed new language:
"Opt-Out: If for some reason you do not want your recognition to appear, or would like it removed from LiSN, please click this link to opt-out: http://lib-highfive.ucsd.edu/optout/xipis-sotun-nafyv-rolil-rabur-felat-mahog-tanah-komol-nadob-buxux"
![screenshot](https://user-images.githubusercontent.com/11340068/75269941-9beabe00-57ae-11ea-958a-4a24dfdf1102.png)

**Comment by jessicahilt** [comment]
From Zen Desk: https://ucsdlibrary.zendesk.com/agent/tickets/639

**Comment by jessicahilt** [comment]
From Zen Desk: https://ucsdlibrary.zendesk.com/agent/tickets/639

**Comment by jessicahilt** [comment]
From Zen Desk: https://ucsdlibrary.zendesk.com/agent/tickets/639

**Comment by jessicahilt** [comment]
From Zen Desk: https://ucsdlibrary.zendesk.com/agent/tickets/639

**Comment by dt-ucsd** [comment]
This is a duplicate request. The work was completed previously. See: https://ucsdlibrary.zendesk.com/agent/tickets/640
