### ISSUE TITLE
Rename APPS_H5_EMAIL_HOST variable

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#373]
### Descriptive summary

Rename the `APPS_H5_EMAIL_HOST` variable. It is misleading, particularly in a future Helm/container world where we might expect that this refers to the host that the email container would be running on.

However, what this variable is actually used for, is explicitly setting the hostname for the application that `ActionMailer` uses when generating links using the Rails url_helpers.

Acceptance Criteria:
* Agreed upon new name
* PR to the application changing the variable name where referenced
* PR to ops-ansible-playbooks mirroring the variable name change

@VivianChu - let me know if you have a name in mind.

**Comment by mcritchlow** [comment]
@VivianChu - I'm thinking maybe something like `RAILS_APPLICATION_HOST` or something like that. Curious what you think. I think it's the `EMAIL` part that really feels wrong and needs changing. So we could also make a smaller change like `APPS_H5_APP_HOST`

**Comment by VivianChu** [comment]
@mcritchlow - I think APPS_H5_APP_HOST is a good name.

**Comment by mcritchlow** [comment]
@VivianChu - ok, i'll make the change and create a branch for ops-ansible-playbooks as well
