### ISSUE TITLE
Tighten Access Control to application, Library folks only

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#38]
### Descriptive summary

Add a check in the SSO code to ensure the authenticated user is a LIBRARY employee. Anyone else should get an error notice that they aren't welcome here (or perhaps something less mean spirited)

### Rationale

This application should only be accessible to Library employees. So this gating should be done for every controller action.

### Expected behavior

A library employee should be able to authenticate and be authorized to CRUD recognitions. A non-library UCSD employee should not.

### Actual behavior
At the moment, if deployed as-is, any UCSD employee would be able to authenticate and be authorized to CRUD recognitions.

**Comment by mcritchlow** [comment]
@VivianChu - I'll add this work to my current `add-employee-persistence` branch. It kinda lines up with some other work in those areas. So if it's OK with you I'll fold this in to that eventual PR (as a separate commit of course)

**Comment by VivianChu** [comment]
@mcritchlow - Sounds good.
