### ISSUE TITLE
Determine whether RSS feed is needed, if so implement

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#39]
### Descriptive summary

There has been discussion but no concrete decision on whether the application should provide an RSS feed that can be consumed by Confluence/LiSN. We need to make this call.

Worth noting is because the application will be behind SSO/LDAP, a 'public' feed that can trivially be consumed by Confluence might be tricky, unless we're ok with either:

1. Letting the feed action/route be 'public' and assume if someone happens to stumble across it all they're getting are 'hi five's' for employees. We could obfuscate the route as well and do a 'security through obscurity' thing.

2. Creating a local account that we allow to access the feed via the application from Confluence. This is a bit nasty too..

### Rationale

Need to determine whether there is a need/user story for providing an RSS feed for the application to be consumed by Confluence.

**Comment by jessicahilt** [comment]
1) Could it work in Boba Fett? Perhaps a simulation to show what will show up when using RSS feed? 

2) With the RSS: Name, department*, and their nomination type (Service & Excellence, Risk Taking). 
Submit Employee Recognition > Application 

3) Blog posts will live in the application where they can click and read the nomination. When viewing the page, it would be great if people didn't have to log in - campus restricted instead.
