### ISSUE TITLE
R&D: Can we pull the employee photo from LDAP?

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#40]
### Descriptive summary

This is an idea I had that might make the design/UI much more interesting when implementing tickets #37 and #36 

will ask Dan

### Rationale

Having a photo of the recognized person seems to be a common design decision other folks have made that have created apps in this context. If we can grab this from LDAP, we're already doing the query so it's just another field to add/persist.

**Comment by mcritchlow** [comment]
@dlasusa says this is possible, or at least the data is available in a record when we have a photo. So we'll need to sort out how to properly query and persist this (which probably gives more push behind a DB table for this in #15 ) But this would be good for UI/design possibilities.

**Comment by dlasusa** [comment]
I had previously extracted photo information from AD and output to an image file using powershell:

```
$SB="OU=Users,OU=University Library,DC=AD,DC=UCSD,DC=EDU"
$list=GET-ADuser -Filter{Thumbnailphoto -like "*"} -SearchBase $SB -properties thumbnailphoto

Foreach ($User in $list)

{

$Directory='C:\temp\ad_photos\'

If ($User.thumbnailphoto)

  {

  $Filename=$Directory+$User.samaccountname+'.jpg'

  [System.Io.File]::WriteAllBytes($Filename, $User.Thumbnailphoto)

  }

}
```

**Comment by mcritchlow** [comment]
This is awesome, than you @dlasusa :clap:

**Comment by mcritchlow** [comment]
@VivianChu - while it's still unclear whether our stakeholders actually want this, i'm going to spend a little time today seeing what would be involved in implementing it. Fortunately we have Dan's powershell code as reference, so i don't think it will be too terrible.
