### ISSUE TITLE
Identify campus DB query to extract employee supervisor(s)

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/hifive#52]
### Descriptive summary
After chatting with @dlasusa and @tmarconi, it's clear that at the moment we cannot rely on LDAP for manager information. However, Tim is pretty sure this data exists in a campus database and that we should get able to get access to it in a similar fashion we do with apps that hit the campus DB2 database(s).

The deliverable for this ticket is a working query (and access control needed) to extract the manager of a given employee (via employee id or UID, whatever makes the most sense).

What we ultimately do with this query is TBD. I personally think it would be ideal to use to populate the `manager` field in LDAP, and then have this application pull from LDAP. This would let other applications needing manager info, say the NERF form, to also pull from LDAP as needed.

### Rationale
Let's make our lives easier, in this small way :raised_hands: 

### Related work
This is a blocker for #15 and #22

**Comment by VivianChu** [comment]
@mcritchlow - This is the query to get supervisor id and employee id.  
SELECT R.SUP_EMPLOYEE_ID, R.EMP_PERSON_ID from ROLES.SUPERVISOR_DEPART_VIEW R where R.ACTIVE = 1 and R.ROLE_NAME = 'ER_SUPERVISOR'
What's our next step? Thanks

**Comment by mcritchlow** [comment]
@VivianChu - Exciting! I think the next step is if you can work with @dlasusa to build a script that can be run nightly to keep the LDAP `manager` field in sync with this database. Once you have that working, my current branch will work as-is.

**Comment by VivianChu** [comment]
@mcritchlow - The previous query returns the employee id and supervisor id.  I use the current query to returns ad username instead.  
SELECT distinct A.networkuserid USERNAME, A.VANITY_EMAIL_LONG UserAdName, A2.networkuserid ManagerID, A2.VANITY_EMAIL_LONG ManagerAdName from ROLES.SUPERVISOR_DEPART_VIEW R LEFT OUTER JOIN AFFILIATES_DW.AFFILIATES_SAFE_ATTRIBUTES A ON R.EMP_PERSON_ID = A.emb_person_id, AFFILIATES_DW.AFFILIATES_SAFE_ATTRIBUTES A2 where R.ACTIVE = 1 and R.ROLE_NAME = 'ER_SUPERVISOR' AND A2.emb_person_id = R.SUP_PERSON_ID ORDER BY USERNAME
